### ISSUE TITLE
`esources` in full swing, prepare for doom!!

### ISSUE THREAD

**Issue by apprehensions** [ehawkvu/kiss-xorg#126]
+ [kiss: remove VERSION markers](https://codeberg.org/kiss-community/kiss/pulls/121)
+ [kiss: don't set DESTDIR in builds](https://codeberg.org/kiss-community/kiss/pulls/122)
+ [*: remove VERSION markers](https://codeberg.org/kiss-community/repo/pulls/137)
+ [*: explicit DESTDIR](https://codeberg.org/kiss-community/repo/pulls/138)

are all going to or have been merged; this will break many repositories once kiss has been updated and bumped; one notable repository is this one, kiss-xorg.

i knew @ehawkvu was prepared for this via `esources`, but now its time to generate. one such starting point is the Xorg packages. where libXmeta/sources-* files are going to be removed or handled by `kiss-esources`. there will no longer be sources symlinks and only esources being symlinked, and `kiss-esources` generating the `sources` file.

**Comment by apprehensions** [comment]
#### No `DESTDIR` set
- [ ] atk
- [ ] bdfedit
- [ ] cgal
- [ ] eigen
- [ ] farbfeld
- [ ] feh
- [ ] fontforge
- [ ] gftp
- [ ] glm
- [ ] gst-plugins-base
- [ ] gstreamer
- [ ] gtk+2
- [ ] gtk-gnutella
- [ ] hexchat
- [ ] libsecret
- [ ] libslirp
- [ ] libspectre
- [ ] meh
- [ ] netsurf-gtk3
- [ ] opencsg
- [ ] openscad
- [ ] otf2bdf
- [ ] qt5-multimedia
- [ ] sasm
- [ ] scons
- [ ] snd
- [ ] srain
- [ ] surf
- [ ] sxcs
- [ ] sylpheed
- [ ] vimb
- [ ] winetricks
- [ ] wyeb
- [ ] xfiles
- [ ] xmenu
- [ ] yajl
- [ ] zircon
- [ ] zutty
- [ ] nvidia
- [ ] citra-emu
- [ ] crispy-doom
- [ ] desmume
- [ ] freeciv
- [ ] melonDS
- [ ] nethack
- [ ] rpcs3
- [ ] visualboyadvance-m
- [ ] xonotic
- [ ] tinyx
- [ ] xrectsel

#### `pkg_source_resolve()`'d found
- [ ] kicad
- [ ] firefox-beta
- [ ] libXmeta
- [ ] libxcvt
- [ ] sowm
- [ ] st
- [ ] xdpyinfo
- [ ] xf86-video-amdgpu
- [ ] xf86-video-intel
- [ ] xf86-video-nouveau
- [ ] xf86-video-vesa
- [ ] xkeyboard-config
- [ ] xorg-font-util
- [ ] xorg-server
- [ ] xorg-util-macros

**Comment by ehawkvu** [comment]
`xorg/` should be taken care of as of 8ee8f4c17a4a1c86a91011712f03ae1e7a4991b5

**Comment by ehawkvu** [comment]
@apprehensions DESTDIRs should now be fixed aswell

**Comment by apprehensions** [comment]
updated, `xcalc` package may be broken

**Comment by ehawkvu** [comment]
I can build and run xcalc fine.

**Comment by apprehensions** [comment]
openbox and xcalc still use esources

the following packages still don't have DESTDIR:
+ lua-filesystem
+ python-pivy
+ qpwgraph
+ stumpwm-contrib
+ stumpwm
+ x11up
+ yaml-cpp
+ ymuse

**Comment by ehawkvu** [comment]
openbox & xcalc are fixed.

yaml-cpp is also fixed, the rest are false positives.

**Comment by apprehensions** [comment]
awesome
